// src/OptimusPrime.jsx
import "./OptimusPrime.css";
import { useState, useRef } from "react";

export const OptimusPrime = () => {
  const [isVisible, setIsVisible] = useState(true);
  const count = useRef(0);

  const hide = () => {
    setIsVisible(!isVisible);
    if (!isVisible) {
      count.current++;
    }
  };

  return (
    <div id="optimus-container">
      <p>{count.current}</p>
      <button onClick={() => hide()}>Hide</button>
      {isVisible && (
        <img
          className="optimus"
          src="https://cdn.shopify.com/s/files/1/0054/4371/5170/products/667pin.png?v=1627414689"
        />
      )}
    </div>
  );
};

// src/components/OptimusPrime.vue
<script setup>
  import {ref} from "vue";

  const isVisible = ref(true);
  const count = ref(0);

  const hide = () => {
    isVisible.value = !isVisible.value;
    if (!isVisible.value) {
      count.value++;
    }
  }
</script>

<template>
  <div id="optimus-container">
    <p>{{ count }}</p>
    <button @click="hide()">Hide</button>
    <img v-if="isVisible" class="optimus"
      src="https://cdn.shopify.com/s/files/1/0054/4371/5170/products/667pin.png?v=1627414689" />
  </div>
</template>

<style scoped>
#optimus-container {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.optimus {
  width: 25%;
  aspect-ratio: 2 / 3;
}
</style>
